version: "3"
services:
 database:
  image: postgres:16.1
  environment:
   - "POSTGRES_USER=postgres"
   - "POSTGRES_PASSWORD=postgres"
   - "POSTGRES_DB=tangerino"
  ports:
   - 5441:5432
  volumes:
   - pg-data:/var/lib/postgresql/data
volumes:
 pg-data:
